DUT ID,SKEW,STATION,SET TEMP,ADC TYPE,SUPPLY LEVEL,LO,pf json load,pf rxcal,pf txcal,status,error code,error source,File Name
150,0,2,-40,0,0,50000000,1,1,1,1,0,,LogInitPassFail CB dut150.xls
220,2,2,-40,0,0,50000000,1,1,1,1,0,,LogInitPassFail CB dut220.xls
121,0,1,-40,1,0,50000000,1,1,0,0,1172,"Invoke Node System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.Inner Exception: Adi.Tpg.EvalClient.LabviewErpcException: Remote procedure call returned non-zero error code.Error source 0, Error number 9729, Recovery action -2. In file C:/Jenkins/workspace/device-driver_api-dll_develop@2/c_src/devices/adrv9001/public/src/adi_adrv9001_cals.c, in function adi_adrv9001_cals_InitCals_Run, on line 104, variable name NULL. Error message: Command error. Adi.Tpg.EvalClient.LabviewErpcException in initCal Control.vi->Init Cal Ctrl CB.vi->Init Cal Ctrl CB.vi.ProxyCallerLabVIEW: (Hex 0x494) A .NET exception occurred in an external assembly. For information about correcting this error, copy the following exception (in bold), and search the Microsoft Developer Network (MSDN) Web site or the Web for a possible explanation.",LogInitPassFail CB_dut121.xls
